# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hexehrs.sip3.jp
canonical: http://hexehrs.sip3.jp/coreFunctions
name: CoreFunctions
title: "CoreFunctions"
description: "CoreFunctions"
# title: Example Title
# description: Example Implementation Guide for getting started with SUSHI
status: active # draft | active | retired | unknown
version: "2024.7.9"
fhirVersion: 5.0.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: NeXEHRS-CPC
  url: http://nexehrs-cpc.jp
  # email: test@example.org
copyright: NeXEHRS-CPC,JAMI
jurisdiction: 'urn:iso:std:iso:3166#JP'

#----------------------------------------
# ページタイトル名称設定
#----------------------------------------
pages:
  index.md:
    title: CoreFunctions
#-------------------------------------
# メニュー設定
#-------------------------------------
menu:
  Home:
    本文: index.html
  Artifacts: 
    Artifacts: artifacts.html
    
#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
  path-expansion-params: '../../input/_resources/exp-params.json'
  active-tables: 'false'
  apply-version: 'false'
  apply-copyright: 'true'
  apply-publisher: 'true'
  apply-contact: 'true'
  apply-license: 'true'
  apply-jurisdiction: 'true'
  show-inherited-invariants: 'true'
  usage-stats-opt-out: 'true'
  excludexml: 'true'
  excludejson: 'false'
  excludettl: 'true'
  excludemap: 'false'
  generate:
    - json
  no-validate:
    - '*/hl7.fhir.jp.core'
#
#  special-url:
#    - http://jpfhir.jp/fhir/core/CodeSystem/JP_JfagyFoodAllergen_CS

  
  