name: Punlishing IG for JFAGY without production of packages
on:
  push:
    branches: 
      - develop
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
      - '.github/workflows/masterIG.yaml'
env:
  release_version : 20240729
jobs:
  turn1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    environment: SSH_PORT_JPFHIR  # JAMI WG アップロードサイトに関するアクセス情報の環境名
    steps:
    - uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v2
      with:
        check-latest: true

    - name: Setup Sushi
      run: |
        sudo npm install -g fsh-sushi
  
    - name: Install Jekyll
      run: |
        sudo apt-get install jekyll
  
    - name: Download IG Publisher
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: '1.6.11'
        path: .
        file: publisher.jar

    - name: Download the file
      uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile1
      with:
        url: "https://jpfhir.jp/fhir/fhir_dotFHIR_packages.tgz"
        target: .
  
    - name: Prepare for using all dependent packages including Jp modified version of hl7.fhir.r4.core Package 
      env:
        JPPACKAGECOREtgz: fhir_dotFHIR_packages.tgz
      run: |
        ls -l .
        pwd
        echo '--1-'
        mkdir -p /home/runner/.fhir
        mv $JPPACKAGECOREtgz /home/runner/.fhir/
        cd /home/runner/.fhir
        tar xzf $JPPACKAGECOREtgz

    - name: cp tgz-temp/*.tgz       
      run: | 
        : # cp tgz-temp/*.tgz /home/runner/.fhir/packages
        : # cd /home/runner/.fhir/packages
        : # tar xzf hl7.terminology.r4-6.0.0.tgz

    - name: Run IG Publisher
      run: | 
        mkdir -p input-cache
        mv ./publisher.jar ./input-cache
        unset DISPLAY
        java -Xmx12G -Djava.awt.headless=true -jar ./input-cache/publisher.jar -ig ig.ini -tx n/a

    - name: prepare gtz files for upload to remote site
      run: | 
        ruby ./script/create_symbolic_link_from_file2url.rb
        : # 次の行のmakeSymbolicLink.bashは、直上のrubyスクリプトによって新たに作成されるbashスクリプトで、symbolic_linkを実際にln -s コマンドを順に実行して作成するスクリプト。
        : # cat makeSymbolicLink.bash
        cd output
        source ../makeSymbolicLink.bash
        : # ls -l
        cd ..
        cp excel_files/*.xlsx .
        tar czf output.tgz output

    - name: ssh key generate
      run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key; ls -l key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TO_JPFHIR }}

    - name: rsync remote-site-deploy
      run: |
        rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_JPFHIR }}" --delete output.tgz excel_files ${{ secrets.JAMIWG_USERID_AT_WEBHOST }}:${{ secrets.JAMIWG_WEBPATH }}/hexehrs.jp/coreFunctions/ --exclude .htaccess
        ssh -i key  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -p ${{ secrets.SSH_PORT_JPFHIR }} ${{ secrets.JAMIWG_USERID_AT_WEBHOST }}   'cd ${{ secrets.JAMIWG_WEBPATH }}/hexehrs.jp/coreFunctions/ ; tar xzf output.tgz'

